spring:
  main.banner-mode: OFF
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      jdbc.time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/shareit"
    username: "postgres"
    password: "dfdkfj83s"

logging:
  level:
    org.springframework:
      orm.jpa: INFO
      orm.jpa.JpaTransactionManager: DEBUG
      transaction: INFO
      transaction.interceptor: TRACE
